import { Track } from "./types";

export const INITIAL_TRACKS: Track[] = [
  {
    id: "1",
    title: "Neon Horizon",
    artist: "SynthWave Pro",
    genre: "Synthwave",
    coverUrl: "https://picsum.photos/seed/synthwave/400/400",
    duration: "4:20",
    isHighQuality: true,
    isDownloaded: false,
  },
  {
    id: "2",
    title: "Deep Pulsation",
    artist: "Minimalist X",
    genre: "Minimal Techno",
    coverUrl: "https://picsum.photos/seed/techno/400/400",
    duration: "6:15",
    isHighQuality: true,
    isDownloaded: false,
  },
  {
    id: "3",
    title: "Ether Breeze",
    artist: "Atmosphere One",
    genre: "Ambient",
    coverUrl: "https://picsum.photos/seed/ambient/400/400",
    duration: "8:45",
    isHighQuality: true,
    isDownloaded: false,
  },
  {
    id: "4",
    title: "Circuit Breaker",
    artist: "Volt Runner",
    genre: "Electro",
    coverUrl: "https://picsum.photos/seed/electro/400/400",
    duration: "3:50",
    isHighQuality: true,
    isDownloaded: false,
  },
  {
    id: "5",
    title: "Liquid Flow",
    artist: "Bass Theory",
    genre: "Drum & Bass",
    coverUrl: "https://picsum.photos/seed/dnb/400/400",
    duration: "5:30",
    isHighQuality: true,
    isDownloaded: false,
  },
];
